local colors = require 'themes.catppuccin-latte'

local colorActive = colors.mauve
local colorInactive = colors.surface1

-- https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on(
  'hyprland.start',
  function() hl.exec_cmd 'uwsm app -s s -- swayosd-server' end
)

-- https://wiki.hypr.land/Configuring/Basics/Monitors/
pcall(require, 'monitors') -- generated by nwg-displays

hl.monitor {
  output = '',
  mode = 'preferred',
  position = 'auto',
  scale = 'auto',
}

-- https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config {
  -- https://wiki.hypr.land/Configuring/Basics/Variables/#general
  general = {
    allow_tearing = true,
    border_size = 2,
    gaps_in = 4,
    gaps_out = 8,
    layout = 'scrolling',
    no_focus_fallback = true,

    col = {
      active_border = colorActive,
      inactive_border = colorInactive,
    },

    -- https://wiki.hypr.land/Configuring/Basics/Variables/#snap
    snap = {
      enabled = true,
      respect_gaps = true,
    },
  },

  -- https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
  decoration = {
    rounding = 8,
  },

  -- https://wiki.hypr.land/Configuring/Basics/Variables/#misc
  misc = {
    focus_on_activate = true,
    font_family = 'FantasqueSansM Nerd Font',
    key_press_enables_dpms = true,
    middle_click_paste = false,
    mouse_move_enables_dpms = true,
    on_focus_under_fullscreen = 0,
  },

  -- https://wiki.hypr.land/Configuring/Basics/Variables/#xwayland
  xwayland = {
    use_nearest_neighbor = false,
  },
}

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
hl.config {
  ecosystem = {
    enforce_permissions = true,
  },
}

hl.permission {
  binary = '/usr/bin/grim',
  type = 'screencopy',
  mode = 'allow',
}

hl.permission {
  binary = '/usr/bin/hyprlock',
  type = 'screencopy',
  mode = 'allow',
}

hl.permission {
  binary = '/usr/bin/still',
  type = 'screencopy',
  mode = 'allow',
}

hl.permission {
  binary = '/usr/lib/xdg-desktop-portal-hyprland',
  type = 'screencopy',
  mode = 'allow',
}

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.config {
  -- https://wiki.hypr.land/Configuring/Basics/Variables/#animations
  animations = {
    enabled = true,
  },
}

hl.curve('easeOutExpo', {
  type = 'bezier',
  points = {
    { 0.16, 1 },
    { 0.3, 1 },
  },
})

hl.animation {
  leaf = 'global',
  enabled = true,
  speed = 3,
  bezier = 'easeOutExpo',
}

hl.animation {
  leaf = 'windows',
  enabled = true,
  speed = 3,
  bezier = 'easeOutExpo',
  style = 'slidefadevert',
}

hl.animation {
  leaf = 'workspaces',
  enabled = true,
  speed = 3,
  bezier = 'easeOutExpo',
  style = 'slidefadevert',
}

hl.animation {
  leaf = 'specialWorkspace',
  enabled = true,
  speed = 3,
  bezier = 'easeOutExpo',
  style = 'slidefadevert 10%',
}

hl.config {
  -- https://wiki.hypr.land/Configuring/Basics/Variables/#input
  input = {
    kb_layout = 'us,ru',
    kb_options = 'grp:alt_space_toggle',

    accel_profile = 'flat',

    -- https://wiki.hypr.land/Configuring/Basics/Variables/#touchpad
    touchpad = {
      natural_scroll = true,
      scroll_factor = 0.4,
      drag_lock = true,
    },
  },

  -- https://wiki.hypr.land/Configuring/Basics/Variables/#gestures
  gestures = {
    workspace_swipe_cancel_ratio = 0.1,
    workspace_swipe_touch = true,
  },
}

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
hl.gesture { fingers = 4, direction = 'vertical', action = 'workspace' }
hl.gesture { fingers = 4, direction = 'horizontal', action = 'scroll_move' }

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
hl.device { name = 'keychron--keychron-link-', sensitivity = -0.5 }
hl.device { name = 'keychron-keychron-m6-', sensitivity = -0.5 }

-- https://wiki.hypr.land/Configuring/Basics/Binds/
hl.config {
  -- https://wiki.hypr.land/Configuring/Basics/Variables/#binds
  binds = {
    workspace_back_and_forth = true,
  },
}

hl.bind(
  'XF86MonBrightnessDown',
  hl.dsp.exec_cmd 'swayosd-client --brightness lower',
  {
    locked = true,
    repeating = true,
  }
)

hl.bind(
  'XF86MonBrightnessUp',
  hl.dsp.exec_cmd 'swayosd-client --brightness raise',
  {
    locked = true,
    repeating = true,
  }
)

hl.bind('XF86AudioPrev', hl.dsp.exec_cmd 'playerctl previous', {
  locked = true,
})

hl.bind('XF86AudioPlay', hl.dsp.exec_cmd 'playerctl play-pause', {
  locked = true,
})

hl.bind('XF86AudioNext', hl.dsp.exec_cmd 'playerctl next', {
  locked = true,
})

hl.bind(
  'XF86AudioMute',
  hl.dsp.exec_cmd 'swayosd-client --output-volume mute-toggle && canberra-gtk-play --id audio-volume-change',
  {
    locked = true,
    repeating = true,
  }
)

hl.bind(
  'XF86AudioLowerVolume',
  hl.dsp.exec_cmd 'swayosd-client --output-volume lower && canberra-gtk-play --id audio-volume-change',
  {
    locked = true,
    repeating = true,
  }
)

hl.bind(
  'XF86AudioRaiseVolume',
  hl.dsp.exec_cmd 'swayosd-client --output-volume raise && canberra-gtk-play --id audio-volume-change',
  {
    locked = true,
    repeating = true,
  }
)

hl.bind('SUPER + RETURN', hl.dsp.exec_cmd 'uwsm app -- kitty --single-instance')
hl.bind('SUPER + R', hl.dsp.exec_cmd 'fuzzel')
hl.bind('SUPER + C', hl.dsp.window.close())
hl.bind('SUPER + N', hl.dsp.exec_cmd 'swaync-client -t')

hl.bind('SUPER + H', hl.dsp.focus { direction = 'left' })
hl.bind('SUPER + J', hl.dsp.focus { direction = 'down' })
hl.bind('SUPER + K', hl.dsp.focus { direction = 'up' })
hl.bind('SUPER + L', hl.dsp.focus { direction = 'right' })

hl.bind('SUPER + SHIFT + H', hl.dsp.window.move { direction = 'left' })
hl.bind('SUPER + SHIFT + J', hl.dsp.window.move { direction = 'down' })
hl.bind('SUPER + SHIFT + K', hl.dsp.window.move { direction = 'up' })
hl.bind('SUPER + SHIFT + L', hl.dsp.window.move { direction = 'right' })

for i = 1, 9 do
  hl.bind('SUPER + ' .. i, hl.dsp.focus { workspace = i })
  hl.bind('SUPER + SHIFT + ' .. i, hl.dsp.window.move { workspace = i })
end

hl.bind('SUPER + 0', hl.dsp.workspace.toggle_special '0')
hl.bind('SUPER + SHIFT + 0', hl.dsp.window.move { workspace = 'special:0' })

hl.bind(
  'SUPER + F',
  hl.dsp.window.fullscreen { action = 'toggle', mode = 'fullscreen' }
)

hl.bind(
  'SUPER + M',
  hl.dsp.window.fullscreen { action = 'toggle', mode = 'maximized' }
)

hl.bind('SUPER + GRAVE', hl.dsp.window.float { action = 'toggle' })
hl.bind('SUPER + P', hl.dsp.window.pseudo { action = 'toggle' })

hl.bind('SUPER + mouse:272', hl.dsp.window.resize(), { mouse = true })
hl.bind('SUPER + SHIFT + mouse:272', hl.dsp.window.drag(), { mouse = true })

hl.bind('SUPER + COMMA', hl.dsp.layout 'colresize -conf')
hl.bind('SUPER + PERIOD', hl.dsp.layout 'colresize +conf')
hl.bind('SUPER + SLASH', hl.dsp.layout 'promote')

local screenshot =
  hl.dsp.exec_cmd "still -p -c 'slurp -d | grim -g- -l0 -' | swappy -f -"

hl.bind('SUPER + S', screenshot)
hl.bind('Print', screenshot)

hl.bind('SUPER + CTRL + Q', hl.dsp.exec_cmd 'loginctl lock-session')

hl.bind(
  'CTRL + ALT + SHIFT + BACKSPACE',
  hl.dsp.exec_cmd 'hyprshutdown --post-cmd uwsm stop'
)

-- https://wiki.hypr.land/Configuring/Basics/Window-Rules/
hl.window_rule { match = { class = '^(hyprland-share-picker)$' }, float = true }
hl.window_rule { match = { class = '^(mpv)$' }, float = true }
hl.window_rule { match = { class = '^(org.gnome.Loupe)$' }, float = true }
hl.window_rule { match = { class = '^(org.gnome.Showtime)$' }, float = true }

hl.window_rule {
  match = { class = '^(org.keepassxc.KeePassXC)$' },
  no_screen_share = true,
}

hl.window_rule {
  match = {
    class = '^(org.telegram.desktop)$',
    title = '^(Просмотр медиа)$',
  },
  float = true,
  fullscreen = true,
}

hl.window_rule {
  match = {
    class = '^(zen)$',
    title = '^(Картинка в картинке)$',
  },
  suppress_event = 'activatefocus maximize',
}

-- https://wiki.hypr.land/Configuring/Basics/Window-Rules/#layer-rules
hl.layer_rule {
  match = { namespace = 'launcher' },
  dim_around = true,
  animation = 'popin 80%',
}

hl.layer_rule { match = { namespace = 'still' }, no_anim = true }

hl.layer_rule {
  match = { namespace = 'swaync-control-center' },
  dim_around = true,
  animation = 'slide right',
}

hl.layer_rule {
  match = { namespace = 'swaync-notification-window' },
  no_anim = true,
}

hl.layer_rule { match = { namespace = 'waybar' }, animation = 'slide top' }
