return {
  {
    'tpope/vim-fugitive',
    dependencies = {
      'tpope/vim-rhubarb',
    },
    cmd = {
      'G',
      'GBrowse',
      'GDelete',
      'GMove',
      'GRemove',
      'GRename',
      'GUnlink',
      'Gcd',
      'Gclog',
      'Gdiffsplit',
      'Gdrop',
      'Gedit',
      'Ggrep',
      'Ghdiffsplit',
      'Git',
      'Glcd',
      'Glgrep',
      'Gllog',
      'Gpedit',
      'Gread',
      'Gsplit',
      'Gtabedit',
      'Gvdiffsplit',
      'Gvsplit',
      'Gwq',
      'Gwrite',
    },
    keys = {
      {
        desc = 'Git: Status',
        '<leader>gs',
        '<Cmd>Git<CR>',
      },
      {
        desc = 'Git: Blame',
        '<leader>gb',
        '<Cmd>Git blame<CR>',
      },
      {
        desc = 'Git: Difftool',
        '<leader>gd',
        '<Cmd>Gvdiffsplit<CR>',
      },
      {
        desc = 'Git: File Log',
        '<leader>gfl',
        '<Cmd>Git log %<CR>',
      },
      {
        desc = 'Git: Log',
        '<leader>gl',
        '<Cmd>Git log<CR>',
      },
      {
        desc = 'Git: External',
        mode = { 'n', 'x' },
        '<leader>gx',
        ':GBrowse<CR>',
      },
    },
  },
  {
    'lewis6991/gitsigns.nvim',
    event = { 'BufReadPre', 'BufNewFile' },
    keys = {
      {
        desc = 'Next change',
        mode = { 'n', 'x' },
        expr = true,
        silent = true,
        ']c',
        function() return vim.wo.diff and ']c' or '<Cmd>Gitsigns next_hunk<CR>' end,
      },
      {
        desc = 'Previous change',
        mode = { 'n', 'x' },
        expr = true,
        silent = true,
        '[c',
        function() return vim.wo.diff and '[c' or '<Cmd>Gitsigns prev_hunk<CR>' end,
      },
      {
        desc = 'Hunk Stage',
        mode = { 'n', 'x' },
        silent = true,
        '<leader>hs',
        ':Gitsigns stage_hunk<CR>',
      },
      {
        desc = 'Hunk Reset',
        mode = { 'n', 'x' },
        silent = true,
        '<leader>hr',
        ':Gitsigns reset_hunk<CR>',
      },
      {
        desc = 'Hunk Undo',
        silent = true,
        '<leader>hu',
        '<Cmd>Gitsigns undo_stage_hunk<CR>',
      },
      {
        desc = 'Stage Buffer',
        silent = true,
        '<leader>hS',
        '<Cmd>Gitsigns stage_buffer<CR>',
      },
      {
        desc = 'Reset Buffer',
        silent = true,
        '<leader>hR',
        '<Cmd>Gitsigns reset_buffer<CR>',
      },
      {
        desc = 'Hunk Preview',
        silent = true,
        '<leader>hp',
        '<Cmd>Gitsigns preview_hunk<CR>',
      },
    },
    opts = {
      attach_to_untracked = true,
      signs_staged_enable = false,
    },
  },
}
