[styles.tables]
headers = { color = "gray" }

[styles.widgets]
border_color = "gray"
selected_border_color = "cyan"
selected_text = { color = "black", bg_color = "white" }
widget_title = { color = "gray" }
