# Fonts (https://sw.kovidgoyal.net/kitty/conf/#fonts)
font_family FantasqueSansM Nerd Font Mono
disable_ligatures cursor

# Text cursor customization (https://sw.kovidgoyal.net/kitty/conf/#text-cursor-customization)
cursor none
cursor_text_color background
cursor_blink_interval -1 ease-in linear
cursor_trail 1

# Scrollback (https://sw.kovidgoyal.net/kitty/conf/#scrollback)
scrollback_pager nvim --cmd 'lua require("faergeek.utils.kitty-scrollback")(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)'

# Mouse (https://sw.kovidgoyal.net/kitty/conf/#mouse)
mouse_hide_wait -1
show_hyperlink_targets yes

# Terminal bell (https://sw.kovidgoyal.net/kitty/conf/#terminal-bell)
enable_audio_bell no
visual_bell_duration 0.25

# Window layout (https://sw.kovidgoyal.net/kitty/conf/#window-layout)
remember_window_size no
initial_window_width 80c
initial_window_height 24c
enabled_layouts splits
placement_strategy top-left
resize_in_steps yes

# Tab bar (https://sw.kovidgoyal.net/kitty/conf/#tab-bar)
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}:{title}"

# Advanced (https://sw.kovidgoyal.net/kitty/conf/#advanced)
close_on_child_death yes
notify_on_cmd_finish unfocused

# OS specific tweaks (https://sw.kovidgoyal.net/kitty/conf/#os-specific-tweaks)
macos_titlebar_color background
macos_option_as_alt both
macos_show_window_title_in window
macos_quit_when_last_window_closed yes

# Keyboard shortcuts (https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts)
clear_all_shortcuts yes

# Clipboard (https://sw.kovidgoyal.net/kitty/conf/#clipboard)
map kitty_mod+c copy_to_clipboard
map cmd+c copy_to_clipboard

map kitty_mod+v paste_from_clipboard
map cmd+v paste_from_clipboard

# Scrolling (https://sw.kovidgoyal.net/kitty/conf/#scrolling)
map kitty_mod+s show_scrollback
map kitty_mod+o show_last_command_output

# Window management (https://sw.kovidgoyal.net/kitty/conf/#window-management)
map kitty_mod+n new_os_window
map cmd+n new_os_window

# Splits
map kitty_mod+enter launch --location=split --cwd=current
map kitty_mod+d layout_action rotate

# Focus
map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window bottom
map kitty_mod+k neighboring_window top
map kitty_mod+l neighboring_window right

# Move
map kitty_mod+alt+h move_window left
map kitty_mod+alt+j move_window bottom
map kitty_mod+alt+k move_window top
map kitty_mod+alt+l move_window right
map kitty_mod+alt+d>w detach_window ask

# Tab management (https://sw.kovidgoyal.net/kitty/conf/#tab-management)
map kitty_mod+t new_tab_with_cwd !neighbor

# Focus
map kitty_mod+] next_tab
map kitty_mod+[ previous_tab
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9

# Move
map kitty_mod+. move_tab_forward
map kitty_mod+, move_tab_backward
map kitty_mod+alt+d>t detach_tab ask

# Font sizes (https://sw.kovidgoyal.net/kitty/conf/#font-sizes)
map kitty_mod+equal change_font_size current +2.0
map kitty_mod+minus change_font_size current -2.0
map kitty_mod+0 change_font_size current 0

# Miscellaneous (https://sw.kovidgoyal.net/kitty/conf/#miscellaneous)
map kitty_mod+m toggle_maximized
map kitty_mod+r load_config_file

include ${KITTY_OS}.conf
