vim.g.mapleader = ' '
vim.g.maplocalleader = '\\'

require 'faergeek.config.status'
require 'faergeek.config.spell'
require 'faergeek.config.options'
require 'faergeek.config.keymaps'
require 'faergeek.config.autocmds'
require 'faergeek.config.sessions'
require 'faergeek.config.lazy'
